import { Inter } from "next/font/google";
import "./globals.css";
import MenuSlider from "@/Components/menuSlider/MenuSlider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl`}>
        <div className="mt-16 flex justify-center align-middle">
          <MenuSlider />
        </div>
        {children}
      </body>
    </html>
  );
}
